### ISSUE TITLE
Extinction conditions

### ISSUE THREAD

**Issue by xxPLxx** [BM32ESRF/LaueNN#3]
I believe that exctinction conditions not predefined in `CrystalParameters.py` are not dealt with correctly. Note that I added my own material with space group 191 (its PrNi5 for full reference) and crashed at generating trainig data via GUI.

Since group 191 has not predefined data, in `CrystalParameters.py -> ApplyExtinctionrules` (line 62 onwards) it satisfies `Extinc.isdecimal()` and so calls `wyckpos_lauetools.py -> testhklcond_generalrules_array` (line 428 onwards).

1st issue is that there `gp[2]` (defined by sorting appropriate wp entry at around 448) is `None`. But in the condition at 452 it is not `'n/a'`, so the cond gives true. But None does not seem to be valid argument for `hklcond_group.findall` (reported as #2).

Assuming there should have been *and* instead of *or* the `return True` statement seems weird, as the expected output of the function is smth like 2dim array. I tried to bypass this by outputting `np.array(((True,),))`, but it than crashes at `utils_lauenn.py -> get_material_data -> dstar_square_2 = np.diag(np.inner(np.inner(H2, metrics), H2))` (line 912), since H2 is only 1x1 array (which I believe is connected to the fact that `ApplyExtinctionrules` got only one `True` instead of expected hkl triplet as described in this paragraph).

Hope I did not misinterpreted the code completely, I am mostly guessing. But all in all a material with space group 191 is not processed correctly and I tried to suggest the reason why it might be so.

**Comment by ravipurohit1991** [comment]
Dear @xxPLxx ,
Thank you for pointing out the bug in the code. This is indeed overlooked while porting the functions from single hkl to array of hkl.

So the space group 191 has no general reflection condition (thats why the gp[2] is None), i.e. it should allow all hkls to be present. And indeed as you pointed out the `return True` is wrong and is not adapted well in case of no general reflection condition exists. Instead of returning True we should be returning all the hkl in the input arguments.  A fix would be to add `return hkl` instead of `return True` in the `wyckpos_lauetools.py -> testhklcond_generalrules_array`. Or to avoid entering in to this loop, the other way would be to define your material with 'no' extinction as condition (as in your case there are no extinction for the spacegroup). 

Also, you are right, it should be an `and` instead of `or` for the hkl condition.

I have fixed this in the code and you should be able to install the new version from `PYPI (pip install lauetoolsnn --upgrade)`.

We will soon write up a wiki to allow users to input their own reflection condition in the `CrystalParameters.py`.

Thank you for reporting this bug,
Regards,
Ravi
